[general]
board = "uno"
# After flashing, open the serial console at 9600 baud.
open-console = true
serial-baudrate = 9600

# For documentation about this file, check here:
# https://github.com/Rahix/avr-hal/blob/main/ravedude/README.md#ravedudetoml-format
